name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: |
          dvc remote modify vkcloud endpointurl ${{ secrets.VKCLOUD_ENDPOINT_URL }} && \
          dvc remote modify vkcloud access_key_id ${{ secrets.VKCLOUD_ACCESS_KEY_ID }} && \
          dvc remote modify vkcloud secret_access_key ${{ secrets.VKCLOUD_SECRET_ACCESS_KEY }} && \
          dvc pull
      - name: Build and push twitter-sentiment trainer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfiles/twitter.trainer.dockerfile
          push: true
          tags: danielto1404/ml-pipe-twitter-sentiment:latest
      - name: Build and push Hashicorp custom image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfiles/hashicorp.vault.dockerfile
          push: true
          tags: danielto1404/hashicorp:latest
      - name: Build and push Vault store credentials custom image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfiles/storing.credentials.dockerfile
          push: true
          tags: danielto1404/vault-store-credentials:latest